(spacemacs/set-leader-keys "ob" 'johnbear724/build)
(spacemacs/set-leader-keys "or" 'johnbear724/run)
;; (spacemacs/set-leader-keys "od" 'johnbear724/push-mark-and-goto-definition)
(spacemacs/set-leader-keys "oy" 'youdao-dictionary-search)
(spacemacs/set-leader-keys "on" 'johnbear724/open-quick-notes)
(spacemacs/set-leader-keys "op" 'johnbear724/open-private-layers)
(spacemacs/set-leader-keys "om" 'johnbear724/switch-to-messages-buffer)
(global-set-key (kbd "C-;") 'company-complete)
